{% set name = "cjdk" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c83bdb06749a2cdee8e0c9ca1612e10b629286a0a48115ecc2e892e072d5315a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  entry_points:
    - cjdk = cjdk.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - click >=8.0
    - progressbar2 >=4.0
    - requests >=2.24

test:
  imports:
    - cjdk
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/cachedjdk/cjdk
  summary: 'Auto-download JDK or JRE and run Java apps from Python or CLI'
  description: |
    cjdk (for "cached JDK") is a Python package and command-line tool to download
    and run JDK (Java Development Kit) or JRE (Java Runtime Environment) distributions.

    Previously used JDKs are kept in the user's cache directory, so that future
    invocations do not require a download.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://cachedjdk.github.io/cjdk/
  dev_url: https://github.com/cachedjdk/cjdk

extra:
  recipe-maintainers:
    - tlambert03
    - ctrueden
    - marktsuchida
